personal_balance_sheet/config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get '/home/index'
  get '/home/form'
  post '/home/submit'
  delete '/home/:id' => 'home#destroy'

  devise_for :users

end

personal_balance_sheet/app/models/data_input.rb
class DataInput < ActiveRecord::Base
end

personal_balance_sheet/app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

personal_balance_sheet/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :money_inputs
  has_many :comments

end

personal_balance_sheet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

personal_balance_sheet/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @datainputs = DataInput.where(user_id: current_user.id)
  end

  def form
    @datainput = DataInput.new
  end

  def submit
    d = DataInput.new(data_input_params)
    d.user_id = current_user.id
    d.save
    redirect_to '/home/index', notice: "Watch it, mister!"
  end

  def destroy
    @datainput = DataInput.find(params[:id])
    @datainput.destroy
    redirect_to '/home/index', notice: 'Money was successfully destroyed.'
  end

  def data_input_params
    params.require(:data_input).permit(:date, :income, :rent, :loans, :insurance, :utilities, :entertainment, :food, :misc, :balance, :comment)
  end
end

personal_balance_sheet/app/helpers/application_helper.rb
module ApplicationHelper
end

personal_balance_sheet/app/helpers/home_helper.rb
module HomeHelper
end

personal_balance_sheet/app/views/application/_form.html.erb
<h1>Personal Balance Sheet</h1>

<div id="myform">
<%= form_tag("/categories", method: "post") do %>
  Date: <br>
  <input type="date" name="date" id="date"><br><br><br>
  Monthly Income: <br>
  <input type="integer" name="monthly_income" id="monthly_income" onchange="updateForm()"><br>
  Rent: <br>
  <input type="integer" name="rent" id="rent" onchange="updateForm()"><br>
  Loans: <br>
  <input type="integer" name="loans" id="loans" onchange="updateForm()"><br>
  Insurance: <br>
  <input type="integer" name="insurance" id="insurance" onchange="updateForm()"><br>
  Utilities: <br>
  <input type="integer" name="utilities" id="utilities" onchange="updateForm()"><br>
  Entertainment: <br>
  <input type="integer" name="entertainment" id="entertainment" onchange="updateForm()"><br>
  Food: <br>
  <input type="integer" name="food" id="food" onchange="updateForm()"><br>
  Misc: <br>
  <input type="integer" name="misc" id="misc" onchange="updateForm()"><br><br>
  Balance: <br>
  <input type="integer" name="balance" id="balance" readonly><br><br>
  Your Comment for this MONTH: <br>
  <textarea name="comment" id="comment" rows="10" tabindex="4"  required=""></textarea><br>

  <!-- <input type="button" name="button" value="Calculate" onclick="myform"> -->
  <input type="submit" value="Save this Information">
<% end %>
</div>

personal_balance_sheet/app/views/home/form.html.erb
<h1>You are preparing your <span id="_month"></span></h1>

<h1>Personal Balance Sheet</h1>

<%= form_for @datainput, url: '/home/submit', html: {class: "money_form"} do |f| %>
  <h3>Date:</h3> <br>
  <%= f.date_field :date %><br><br><br>
  <h3>Monthly Income:</h3> <br>
  <%= f.number_field :income, {:id => "income", :onchange => "updateForm()"} %><br>
  <h3>Rent:</h3> <br>
  <%= f.number_field :rent, {:id => "rent", :onchange => "updateForm()"} %><br>
  <h3>Loans:</h3> <br>
  <%= f.number_field :loans, {:id => "loans", :onchange => "updateForm()"} %><br>
  <h3>Insurance:</h3> <br>
  <%= f.number_field :insurance, {:id => "insurance", :onchange => "updateForm()"} %><br>
  <h3>Utilities:</h3> <br>
  <%= f.number_field :utilities, {:id => "utilities", :onchange => "updateForm()"} %><br>
  <h3>Entertainment:</h3> <br>
  <%= f.number_field :entertainment, {:id => "entertainment", :onchange => "updateForm()"} %><br>
  <h3>Food:</h3> <br>
  <%= f.number_field :food, {:id => "food", :onchange => "updateForm()"} %><br>
  <h3>Misc:</h3> <br>
  <%= f.number_field :misc, {:id => "misc", :onchange => "updateForm()"}%><br><br>
  <h3>Balance:</h3> <br>
  <%= f.number_field :balance, {:id => "balance", :readonly => "true"} %><br><br>
  <h3>What happened this Month?</h3> <br>
  <%= f.text_area :comment, size: "60x12" %><br>
  <%= f.submit "Save this Information" %>
  <%= link_to '<button type="button">Cancel</button>'.html_safe, home_index_path %>
<% end %>

<script>
window.onload = function () {
  onload()
}
</script>

personal_balance_sheet/app/views/home/index.html.erb
<%= link_to '<button type="button">New Finance Sheet</button>'.html_safe, home_form_path %>

<h1>Welcome to your Financial Planning Page</h1>

<% @datainputs.each do |data_input| %>
  <div class="money_form">
  <h3>Date</h3>
  <div><%= data_input.date %></div>
  <h3>Income</h3>
  <div><%= data_input.income %></div>
  <h3>Rent</h3>
  <div><%= data_input.rent %></div>
  <h3>Loans</h3>
  <div><%= data_input.loans %></div>
  <h3>Utilities</h3>
  <div><%= data_input.utilities %></div>
  <h3>Entertainment</h3>
  <div><%= data_input.entertainment %></div>
  <h3>Food</h3>
  <div><%= data_input.food %></div>
  <h3>Misc</h3>
  <div><%= data_input.misc %></div>
  <h3>Balance</h3>
  <div><%= data_input.balance %></div>
  <h3>Comment</h3>
  <div><%= data_input.comment %></div><br><br><br>
  <%= button_to('Delete This Sheet', '/home/' + data_input.id.to_s, method: "delete", remote: true, data: { confirm: 'Are you sure?', disable_with: 'loading...' }) %>
  </div>
<%end %>

personal_balance_sheet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PersonalBalanceSheet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="log">
  <% if user_signed_in? %>
      Signed in as <%= current_user.email %>.
      <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
  <% else %>
      <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

personal_balance_sheet/app/views/money_input/_form.html.erb
# <%= link_to "Create Form", money_input %>

<h1>You are preparing your <span id="_month"></span></h1>

<h1>Personal Balance Sheet</h1>

<div id="myform">
<%= form_tag("/categories", method: "post") do %>
  Date: <br>
  <input type="date" name="date" id="date"><br><br><br>
  Monthly Income: <br>
  <input type="integer" name="monthly_income" id="monthly_income" onchange="updateForm()"><br>
  Rent: <br>
  <input type="integer" name="rent" id="rent" onchange="updateForm()"><br>
  Loans: <br>
  <input type="integer" name="loans" id="loans" onchange="updateForm()"><br>
  Insurance: <br>
  <input type="integer" name="insurance" id="insurance" onchange="updateForm()"><br>
  Utilities: <br>
  <input type="integer" name="utilities" id="utilities" onchange="updateForm()"><br>
  Entertainment: <br>
  <input type="integer" name="entertainment" id="entertainment" onchange="updateForm()"><br>
  Food: <br>
  <input type="integer" name="food" id="food" onchange="updateForm()"><br>
  Misc: <br>
  <input type="integer" name="misc" id="misc" onchange="updateForm()"><br><br>
  Balance: <br>
  <input type="integer" name="balance" id="balance" readonly><br><br>
  Your Comment for this MONTH: <br>
  <textarea name="comment" id="comment" rows="10" tabindex="4"  required=""></textarea><br>

  <!-- <input type="button" name="button" value="Calculate" onclick="myform"> -->
  <input type="submit" value="Save this Information">
<% end %>
</div>

<script>
window.onload = function () {
  onload()
}
</script>